server:
  port: 8080
spring:
  application:
    name: microserv-gateway
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microserv-maintenance
          uri: http://localhost:8090
          predicates:
            - Path=/api/maintenance**
        - id: microserv-scooter
          uri: lb://microserv-scooter
          predicates:
            - Path=/api/scooter/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true