server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: microserv-maintenance

datasource:
  url: jdbc:mysql://localhost:3306/Integrador4?useSSL=false&allowPublicKeyRetrieval=true
  username: user
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE