version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mi_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario    # Nombre de usuario root
      MONGO_INITDB_ROOT_PASSWORD: contraseña # Contraseña del usuario root
    volumes:
      - mongodb_data:/data/db      # Volumen para persistir los datos

volumes:
  mongodb_data: